//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lykke.Service.HFT.Core.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lykke.Service.HFT.Core.Strings.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already processed.
        /// </summary>
        internal static string AlreadyProcessed {
            get {
                return ResourceManager.GetString("AlreadyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request.
        /// </summary>
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance lower than reserved.
        /// </summary>
        internal static string BalanceLowerThanReserved {
            get {
                return ResourceManager.GetString("BalanceLowerThanReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try to send higher order.
        /// </summary>
        internal static string Dust {
            get {
                return ResourceManager.GetString("Dust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid fee.
        /// </summary>
        internal static string InvalidFee {
            get {
                return ResourceManager.GetString("InvalidFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input field.
        /// </summary>
        internal static string InvalidInputField {
            get {
                return ResourceManager.GetString("InvalidInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid price.
        /// </summary>
        internal static string InvalidPrice {
            get {
                return ResourceManager.GetString("InvalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order leads to negative spread.
        /// </summary>
        internal static string LeadToNegativeSpread {
            get {
                return ResourceManager.GetString("LeadToNegativeSpread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low balance.
        /// </summary>
        internal static string LowBalance {
            get {
                return ResourceManager.GetString("LowBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No liquidity.
        /// </summary>
        internal static string NoLiquidity {
            get {
                return ResourceManager.GetString("NoLiquidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough funds.
        /// </summary>
        internal static string NotEnoughFunds {
            get {
                return ResourceManager.GetString("NotEnoughFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous not found.
        /// </summary>
        internal static string NotFoundPrevious {
            get {
                return ResourceManager.GetString("NotFoundPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced.
        /// </summary>
        internal static string Replaced {
            get {
                return ResourceManager.GetString("Replaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved volume higher than balance.
        /// </summary>
        internal static string ReservedVolumeHigherThanBalance {
            get {
                return ResourceManager.GetString("ReservedVolumeHigherThanBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime error.
        /// </summary>
        internal static string RuntimeError {
            get {
                return ResourceManager.GetString("RuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime error {0}.
        /// </summary>
        internal static string RuntimeErrorX {
            get {
                return ResourceManager.GetString("RuntimeErrorX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown asset.
        /// </summary>
        internal static string UnknownAsset {
            get {
                return ResourceManager.GetString("UnknownAsset", resourceCulture);
            }
        }
    }
}
