// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.HFT.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssetPairModel
    {
        /// <summary>
        /// Initializes a new instance of the AssetPairModel class.
        /// </summary>
        public AssetPairModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetPairModel class.
        /// </summary>
        public AssetPairModel(int accuracy, int invertedAccuracy, double minVolume, double minInvertedVolume, string id = default(string), string name = default(string), string baseAssetId = default(string), string quotingAssetId = default(string))
        {
            Id = id;
            Name = name;
            Accuracy = accuracy;
            InvertedAccuracy = invertedAccuracy;
            BaseAssetId = baseAssetId;
            QuotingAssetId = quotingAssetId;
            MinVolume = minVolume;
            MinInvertedVolume = minInvertedVolume;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Accuracy")]
        public int Accuracy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InvertedAccuracy")]
        public int InvertedAccuracy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseAssetId")]
        public string BaseAssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuotingAssetId")]
        public string QuotingAssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MinVolume")]
        public double MinVolume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MinInvertedVolume")]
        public double MinInvertedVolume { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
