// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.HFT.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ErrorModel
    {
        /// <summary>
        /// Initializes a new instance of the ErrorModel class.
        /// </summary>
        public ErrorModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ErrorModel class.
        /// </summary>
        /// <param name="code">Possible values include: 'InvalidInputField',
        /// 'Ok', 'LowBalance', 'AlreadyProcessed', 'UnknownAsset',
        /// 'NoLiquidity', 'NotEnoughFunds', 'Dust',
        /// 'ReservedVolumeHigherThanBalance', 'NotFound',
        /// 'BalanceLowerThanReserved', 'LeadToNegativeSpread',
        /// 'PriceGapTooHigh', 'RuntimeError'</param>
        public ErrorModel(ErrorCodeType code, string field = default(string), string message = default(string))
        {
            Code = code;
            Field = field;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'InvalidInputField', 'Ok',
        /// 'LowBalance', 'AlreadyProcessed', 'UnknownAsset', 'NoLiquidity',
        /// 'NotEnoughFunds', 'Dust', 'ReservedVolumeHigherThanBalance',
        /// 'NotFound', 'BalanceLowerThanReserved', 'LeadToNegativeSpread',
        /// 'PriceGapTooHigh', 'RuntimeError'
        /// </summary>
        [JsonProperty(PropertyName = "Code")]
        public ErrorCodeType Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Field")]
        public string Field { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
