// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.HFT.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Fee
    {
        /// <summary>
        /// Initializes a new instance of the Fee class.
        /// </summary>
        public Fee()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Fee class.
        /// </summary>
        /// <param name="type">Possible values include: 'Unknown', 'Absolute',
        /// 'Relative'</param>
        public Fee(double amount, FeeType type)
        {
            Amount = amount;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double Amount { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Unknown', 'Absolute',
        /// 'Relative'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public FeeType Type { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
