// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.HFT.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for FeeType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FeeType
    {
        [EnumMember(Value = "Unknown")]
        Unknown,
        [EnumMember(Value = "Absolute")]
        Absolute,
        [EnumMember(Value = "Relative")]
        Relative
    }
    internal static class FeeTypeEnumExtension
    {
        internal static string ToSerializedValue(this FeeType? value)
        {
            return value == null ? null : ((FeeType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this FeeType value)
        {
            switch( value )
            {
                case FeeType.Unknown:
                    return "Unknown";
                case FeeType.Absolute:
                    return "Absolute";
                case FeeType.Relative:
                    return "Relative";
            }
            return null;
        }

        internal static FeeType? ParseFeeType(this string value)
        {
            switch( value )
            {
                case "Unknown":
                    return FeeType.Unknown;
                case "Absolute":
                    return FeeType.Absolute;
                case "Relative":
                    return FeeType.Relative;
            }
            return null;
        }
    }
}
