// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.HFT.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for HistoryOperationState.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum HistoryOperationState
    {
        [EnumMember(Value = "InProgress")]
        InProgress,
        [EnumMember(Value = "Finished")]
        Finished,
        [EnumMember(Value = "Canceled")]
        Canceled,
        [EnumMember(Value = "Failed")]
        Failed
    }
    internal static class HistoryOperationStateEnumExtension
    {
        internal static string ToSerializedValue(this HistoryOperationState? value)
        {
            return value == null ? null : ((HistoryOperationState)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this HistoryOperationState value)
        {
            switch( value )
            {
                case HistoryOperationState.InProgress:
                    return "InProgress";
                case HistoryOperationState.Finished:
                    return "Finished";
                case HistoryOperationState.Canceled:
                    return "Canceled";
                case HistoryOperationState.Failed:
                    return "Failed";
            }
            return null;
        }

        internal static HistoryOperationState? ParseHistoryOperationState(this string value)
        {
            switch( value )
            {
                case "InProgress":
                    return HistoryOperationState.InProgress;
                case "Finished":
                    return HistoryOperationState.Finished;
                case "Canceled":
                    return HistoryOperationState.Canceled;
                case "Failed":
                    return HistoryOperationState.Failed;
            }
            return null;
        }
    }
}
