// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.HFT.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HistoryTradeModel
    {
        /// <summary>
        /// Initializes a new instance of the HistoryTradeModel class.
        /// </summary>
        public HistoryTradeModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HistoryTradeModel class.
        /// </summary>
        public HistoryTradeModel(System.DateTime dateTime, double price, double amount, string id = default(string), string limitOrderId = default(string), string marketOrderId = default(string), string assetId = default(string), string state = default(string))
        {
            Id = id;
            DateTime = dateTime;
            LimitOrderId = limitOrderId;
            MarketOrderId = marketOrderId;
            Price = price;
            Amount = amount;
            AssetId = assetId;
            State = state;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateTime")]
        public System.DateTime DateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LimitOrderId")]
        public string LimitOrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MarketOrderId")]
        public string MarketOrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Price")]
        public double Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "State")]
        public string State { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
