// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.HFT.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OrderStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderStatus
    {
        [EnumMember(Value = "All")]
        All,
        [EnumMember(Value = "Open")]
        Open,
        [EnumMember(Value = "InOrderBook")]
        InOrderBook,
        [EnumMember(Value = "Processing")]
        Processing,
        [EnumMember(Value = "Matched")]
        Matched,
        [EnumMember(Value = "Cancelled")]
        Cancelled,
        [EnumMember(Value = "Rejected")]
        Rejected
    }
    internal static class OrderStatusEnumExtension
    {
        internal static string ToSerializedValue(this OrderStatus? value)
        {
            return value == null ? null : ((OrderStatus)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OrderStatus value)
        {
            switch( value )
            {
                case OrderStatus.All:
                    return "All";
                case OrderStatus.Open:
                    return "Open";
                case OrderStatus.InOrderBook:
                    return "InOrderBook";
                case OrderStatus.Processing:
                    return "Processing";
                case OrderStatus.Matched:
                    return "Matched";
                case OrderStatus.Cancelled:
                    return "Cancelled";
                case OrderStatus.Rejected:
                    return "Rejected";
            }
            return null;
        }

        internal static OrderStatus? ParseOrderStatus(this string value)
        {
            switch( value )
            {
                case "All":
                    return OrderStatus.All;
                case "Open":
                    return OrderStatus.Open;
                case "InOrderBook":
                    return OrderStatus.InOrderBook;
                case "Processing":
                    return OrderStatus.Processing;
                case "Matched":
                    return OrderStatus.Matched;
                case "Cancelled":
                    return OrderStatus.Cancelled;
                case "Rejected":
                    return OrderStatus.Rejected;
            }
            return null;
        }
    }
}
