// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.HFT.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class OrderBook
    {
        /// <summary>
        /// Initializes a new instance of the OrderBook class.
        /// </summary>
        public OrderBook()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OrderBook class.
        /// </summary>
        public OrderBook(bool isBuy, System.DateTime timestamp, string assetPair = default(string), IList<VolumePrice> prices = default(IList<VolumePrice>))
        {
            AssetPair = assetPair;
            IsBuy = isBuy;
            Timestamp = timestamp;
            Prices = prices;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPair")]
        public string AssetPair { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsBuy")]
        public bool IsBuy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Timestamp")]
        public System.DateTime Timestamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Prices")]
        public IList<VolumePrice> Prices { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Prices != null)
            {
                foreach (var element in Prices)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
